### ISSUE TITLE
How to self sign csr preserving qcStatements

### ISSUE THREAD

**Issue by matteopessina** [creditkudos/eidas#23]
Hi,
first of all thank you for this project, which really helped me.
While csr generated with your tool contains qcStatements, when I try to generate from it a self-signed certificate those extensions are not copied into the certificate.
`openssl x509 -req -days 3650 -in out.csr -signkey out.key -out out.crt`
Is there a way to self-sign it preserving eidas extensions?

**Comment by hatstand** [comment]
The signing process itself is somewhat out of scope for this project. I don't really know why OpenSSL would drop the extensions either. You might have more luck signing certs with go's APIs instead of the `openssl` command line: https://golang.org/pkg/crypto/x509/#CreateCertificate
