### ISSUE TITLE
Could not upload OBWAC and OBSEAL in open banking

### ISSUE THREAD

**Issue by madhumithapenmetsa** [creditkudos/eidas#27]
I am trying to generate a csr file using the config file for openbanking in openssl in windows10 .
**In newer openssl version OID 2.5.4.97 is reserved for organizationIdentifier, so you can change your obwac.conf by removing the OID and it should work.**
with OID we are unable to generate the csr file.so by removing the OID i m able to generate the csr file.But as OID is a mandatory in the CSR the openbanking is not accepting the certificate.Can some one help??

**Comment by hatstand** [comment]
This is a tool for generating CSRs _without_ using OpenSSL. If you want to do that, instructions are in the README.
